version: "3"
services:
  api:
    image: t1_company_test:latest
    container_name: t1_company_test
    build: .
    ports:
      - 6080:6080
    healthcheck:
      test: [ "CMD-SHELL", "poetry run python3 cli_commands/api_healthcheck.py" ]
      interval: 10s
      timeout: 5s
      retries: 5